name: Deployment

on:
  workflow_dispatch:
    inputs:
      build_number:
        default: '10'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
      url: 'https://calibo.com'

    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
          HOSTNAME: ${{ secrets.MACHINE_IP  }}
          USER_NAME: ${{ secrets.MACHINE_USERNAME  }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REGION: "us-east-1"

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            # export access key and
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
            echo "Considering that we have AWS CLI already present ${ECR_REGION}"
            aws --version 
            docker login -u AWS -p $(aws ecr get-login-password --region "us-east-1") 781950061287.dkr.ecr.us-east-1.amazonaws.com
            docker run -d -p 8080:8082 ${{ secrets.REPOSITORY_URL}}/${{ secrets.IMAGE_NAME }}:${{ github.event.inputs.build_number }}
            docker ps
          '
